version: '2'

services:
  postgres:
    image: 'postgres:13.0-alpine'
    environment:
      POSTGRES_DB: alvin
      POSTGRES_USER: alvin
      POSTGRES_PASSWORD: alvin
  redis:
    image: 'redis:6.0.8-alpine'
  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    environment:
      DATABASE_URL: postgres://alvin:alvin@postgres:5432/alvin?pool=25&encoding=unicode&schema_search_path=public
      DEVISE_JWT_SECRET_KEY: RANDOM_SECRET
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/1
      # generate by rails secret
      SECRET_KEY_BASE: 1a5a0b2465d2b02807afbb953efd0d6eef86a4e92a6a905a40f182b328e484879c413984311bc94588b5308fa80dbfaf770ab6f44b503dde57e6216bfa38c03c
